cabal-version: 3.0
name:          hilal
version:       0.1.0.0
build-type:    Simple
extra-source-files: schema.sql, static/*.css

common shared
  default-language:   GHC2021
  default-extensions: AllowAmbiguousTypes, DataKinds, OverloadedStrings, TemplateHaskell
  ghc-options:        -Wall -Wcompat -Wno-unused-do-bind
  build-depends:      base >=4.17 && <5

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    Hilal.App
    Hilal.Assets
    Hilal.Auth
    Hilal.DB
    Hilal.Edit
    Hilal.JSON
    Hilal.Migrate
    Hilal.Query
    Hilal.Time
    Hilal.Types
    Hilal.Views
  build-depends:   aeson
                 , bytestring
                 , cookie
                 , crypton
                 , direct-sqlite
                 , http-types
                 , lucid2
                 , file-embed
                 , sqlite-simple
                 , scotty
                 , text
                 , time
                 , tz
                 , tzdata
                 , wai

executable hilal
  import:         shared
  hs-source-dirs: app
  main-is:        Main.hs
  build-depends:  hilal
                , text
                , warp
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N

test-suite test
  import:         shared
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Tests.hs
  build-depends:  hilal
                , aeson
                , bytestring
                , hspec
                , hspec-wai
                , http-types
                , sqlite-simple
                , time
                , lucid2
                , text
                , tz
                , wai
                , wai-extra
                , temporary