#!/usr/bin/env python3
"""Generate src/Hilal/HijriTable.hs from the Umm al-Qura calendar.

Requires the hijridate package: pip install hijridate
Run from the repository root: python3 tools/hijri_table.py > src/Hilal/HijriTable.hs
"""

from hijridate import Hijri

FIRST_YEAR = 1445
LAST_YEAR = 1475

months = []
for year in range(FIRST_YEAR, LAST_YEAR + 1):
    for month in range(1, 13):
        months.append((year, month))
months.append((LAST_YEAR + 1, 1))

print("module Hilal.HijriTable (monthStarts) where")
print()
print("import Data.Time (Day, fromGregorian)")
print()
print("-- The first day of each month of the Umm al-Qura calendar,")
print("-- " + str(FIRST_YEAR) + " to " + str(LAST_YEAR) + " AH, as (year, month, Gregorian date).")
print("-- The last entry, Muharram " + str(LAST_YEAR + 1) + ", only marks where " + str(LAST_YEAR) + " ends.")
print("-- Generated by tools/hijri_table.py. Do not edit by hand.")
print("monthStarts :: [(Int, Int, Day)]")
print("monthStarts =")

for index, (year, month) in enumerate(months):
    g = Hijri(year, month, 1).to_gregorian()
    prefix = "  [ " if index == 0 else "  , "
    print(prefix + "(" + str(year) + ", " + str(month) + ", fromGregorian "
          + str(g.year) + " " + str(g.month) + " " + str(g.day) + ")")
print("  ]")
